image: registry.gitlab.com/sodaru/container/sodaru/ci-nodejs

stages:
  - test
  - publish
  - deploy-pages

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules

before_script:
  - npm i

test:
  stage: test
  script:
    - npm test
  only:
    - develop

pages:
  stage: deploy-pages
  script:
    - echo "NEXT_PUBLIC_DISABLE_MUIEXT_IMAGE_OPTIMIZATION=true" > .env.local
    - npx next build
    - npx next export
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - tags

publish:
  stage: publish
  cache: []
  script:
    - git describe --exact-match | grep ^v && npm publish
  only:
    - tags
